"""
Plot CT-derived j-wave acoustic maps generated by brain_ct_to_jwave_acoustics.py.

Inputs expected in --input-dir:
  - hu_xyz.npy
  - sound_speed_xyz.npy
  - density_xyz.npy
  - attenuation_db_cm_mhz_xyz.npy
  - metadata.json (optional)
  - tissue_stats.csv (optional)

Outputs:
  - map_slices_hu.png
  - map_slices_sound_speed.png
  - map_slices_density.png
  - map_slices_attenuation.png
  - map_histograms.png
  - map_overview.png
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import matplotlib.pyplot as plt


def _load_array(path: Path, name: str) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Missing required file: {path}")
    arr = np.load(path)
    if arr.ndim != 3:
        raise ValueError(f"{name} must be 3D, got shape={arr.shape}")
    return arr


def _slice_triplet(vol_xyz: np.ndarray, xyz: Tuple[int, int, int]):
    x, y, z = xyz
    xy = vol_xyz[:, :, z].T
    xz = vol_xyz[:, y, :].T
    yz = vol_xyz[x, :, :].T
    return xy, xz, yz


def _robust_limits(vol: np.ndarray, p_lo: float = 1.0, p_hi: float = 99.0):
    vals = vol[np.isfinite(vol)]
    if vals.size == 0:
        return 0.0, 1.0
    vmin = float(np.percentile(vals, p_lo))
    vmax = float(np.percentile(vals, p_hi))
    if not np.isfinite(vmin) or not np.isfinite(vmax) or vmin == vmax:
        return float(np.min(vals)), float(np.max(vals) + 1e-6)
    return vmin, vmax


def plot_map_slices(
    arr_xyz: np.ndarray,
    name: str,
    unit: str,
    cmap: str,
    out_path: Path,
    spacing_xyz_mm: Tuple[float, float, float],
) -> None:
    nx, ny, nz = arr_xyz.shape
    center = (nx // 2, ny // 2, nz // 2)
    xy, xz, yz = _slice_triplet(arr_xyz, center)
    sx, sy, sz = spacing_xyz_mm
    extent_xy = [0, nx * sx, 0, ny * sy]
    extent_xz = [0, nx * sx, 0, nz * sz]
    extent_yz = [0, ny * sy, 0, nz * sz]
    vmin, vmax = _robust_limits(arr_xyz)

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    im = axes[0].imshow(xy, origin="lower", cmap=cmap, extent=extent_xy, vmin=vmin, vmax=vmax)
    axes[0].set_title(f"{name} XY @ z={center[2]}")
    axes[0].set_xlabel("x (mm)")
    axes[0].set_ylabel("y (mm)")
    plt.colorbar(im, ax=axes[0], fraction=0.046, label=unit)

    im = axes[1].imshow(xz, origin="lower", cmap=cmap, extent=extent_xz, vmin=vmin, vmax=vmax)
    axes[1].set_title(f"{name} XZ @ y={center[1]}")
    axes[1].set_xlabel("x (mm)")
    axes[1].set_ylabel("z (mm)")
    plt.colorbar(im, ax=axes[1], fraction=0.046, label=unit)

    im = axes[2].imshow(yz, origin="lower", cmap=cmap, extent=extent_yz, vmin=vmin, vmax=vmax)
    axes[2].set_title(f"{name} YZ @ x={center[0]}")
    axes[2].set_xlabel("y (mm)")
    axes[2].set_ylabel("z (mm)")
    plt.colorbar(im, ax=axes[2], fraction=0.046, label=unit)

    plt.suptitle(f"{name} slices")
    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_histograms(maps: Dict[str, np.ndarray], out_path: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(12, 9))
    keys = ["HU", "sound_speed", "density", "attenuation"]
    units = {
        "HU": "HU",
        "sound_speed": "m/s",
        "density": "kg/m^3",
        "attenuation": "dB/cm/MHz",
    }

    for ax, key in zip(axes.reshape(-1), keys):
        arr = maps[key]
        vals = arr[np.isfinite(arr)].ravel()
        if vals.size == 0:
            ax.set_title(f"{key} (no finite data)")
            continue
        lo, hi = np.percentile(vals, [0.5, 99.5])
        clipped = vals[(vals >= lo) & (vals <= hi)]
        ax.hist(clipped, bins=120, alpha=0.85)
        ax.set_title(f"{key} histogram")
        ax.set_xlabel(units[key])
        ax.set_ylabel("count")
        ax.grid(alpha=0.2)

    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def plot_overview(maps: Dict[str, np.ndarray], spacing_xyz_mm: Tuple[float, float, float], out_path: Path) -> None:
    hu = maps["HU"]
    c = maps["sound_speed"]
    rho = maps["density"]
    att = maps["attenuation"]
    nx, ny, nz = hu.shape
    center = (nx // 2, ny // 2, nz // 2)

    hu_xy, _, _ = _slice_triplet(hu, center)
    c_xy, _, _ = _slice_triplet(c, center)
    rho_xy, _, _ = _slice_triplet(rho, center)
    att_xy, _, _ = _slice_triplet(att, center)
    sx, sy, _ = spacing_xyz_mm
    extent = [0, nx * sx, 0, ny * sy]

    fig, axes = plt.subplots(2, 2, figsize=(14, 11))
    items = [
        ("HU", hu_xy, "gray"),
        ("sound speed (m/s)", c_xy, "viridis"),
        ("density (kg/m^3)", rho_xy, "viridis"),
        ("attenuation (dB/cm/MHz)", att_xy, "magma"),
    ]
    for ax, (title, img, cmap) in zip(axes.reshape(-1), items):
        vmin, vmax = _robust_limits(img)
        im = ax.imshow(img, origin="lower", cmap=cmap, extent=extent, vmin=vmin, vmax=vmax)
        ax.set_title(title)
        ax.set_xlabel("x (mm)")
        ax.set_ylabel("y (mm)")
        plt.colorbar(im, ax=ax, fraction=0.046)

    plt.suptitle("CT-derived j-wave maps (center XY slices)")
    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def _load_spacing(input_dir: Path) -> Tuple[float, float, float]:
    meta_path = input_dir / "metadata.json"
    if meta_path.exists():
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        spacing = meta.get("spacing_xyz_mm")
        if isinstance(spacing, list) and len(spacing) == 3:
            return float(spacing[0]), float(spacing[1]), float(spacing[2])
    return 1.0, 1.0, 1.0


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot CT-derived j-wave property maps.")
    parser.add_argument(
        "--input-dir",
        required=True,
        help="Directory containing hu_xyz.npy/sound_speed_xyz.npy/density_xyz.npy/attenuation_db_cm_mhz_xyz.npy",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory for plots (default: --input-dir/plots)",
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir).expanduser().resolve()
    out_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else (input_dir / "plots")
    out_dir.mkdir(parents=True, exist_ok=True)

    hu = _load_array(input_dir / "hu_xyz.npy", "HU")
    c = _load_array(input_dir / "sound_speed_xyz.npy", "sound_speed")
    rho = _load_array(input_dir / "density_xyz.npy", "density")
    att = _load_array(input_dir / "attenuation_db_cm_mhz_xyz.npy", "attenuation")
    spacing_xyz_mm = _load_spacing(input_dir)

    maps = {
        "HU": hu,
        "sound_speed": c,
        "density": rho,
        "attenuation": att,
    }

    plot_map_slices(hu, "HU", "HU", "gray", out_dir / "map_slices_hu.png", spacing_xyz_mm)
    plot_map_slices(c, "sound speed", "m/s", "viridis", out_dir / "map_slices_sound_speed.png", spacing_xyz_mm)
    plot_map_slices(rho, "density", "kg/m^3", "viridis", out_dir / "map_slices_density.png", spacing_xyz_mm)
    plot_map_slices(
        att,
        "attenuation",
        "dB/cm/MHz",
        "magma",
        out_dir / "map_slices_attenuation.png",
        spacing_xyz_mm,
    )
    plot_histograms(maps, out_dir / "map_histograms.png")
    plot_overview(maps, spacing_xyz_mm, out_dir / "map_overview.png")

    print("[ok] Saved plots:")
    for name in [
        "map_slices_hu.png",
        "map_slices_sound_speed.png",
        "map_slices_density.png",
        "map_slices_attenuation.png",
        "map_histograms.png",
        "map_overview.png",
    ]:
        print(f"  - {out_dir / name}")


if __name__ == "__main__":
    main()

